# GENERAL & NAVs
site_name: Plexosoft Docs
nav:
  - Home: index.md
  - Design:
      - Design Thinking:
          - Overview: design-thinking/overview.md
          - Idea Outline: design-thinking/idea-outline/idea_outline.md
          - Empathy: design-thinking/empathy/empathy.md
          - Personas: design-thinking/personas/personas.md
          - Definition: design-thinking/definition/definition.md
          - Persona: design-thinking/persona/persona.md
          - Ideate: design-thinking/ideate/ideate.md
          - Conclusion: design-thinking/conclusion/conclusion.md
          - PoC Prototype: design-thinking/PoC/poc.md
      - User-Centric Design:
          - Overview: user-centric/overview.md
          - Strategy: user-centric/strategy/strategy.md
          - Scope: user-centric/scope/scope.md
          - Structure: user-centric/structure/structure.md
          - Skeleton: user-centric/skeleton/skeleton.md
          - Surface: user-centric/surface/surface.md
      - Entity Relationship Diagram ERD:
          - Overview: erd/erd.md
          - Diagram: erd/diagram/diagram.md
          - Table Model: erd/table-model/table_model.md
          - Developer Experience: erd/dev-experience/dev_experience.md
  - Development:
      - Agile Development: agile-development/agile_development.md
  - Features:
      - Actual Features: actual-features/actual_features.md
      - Future Features: future-features/future_features.md
  - Tech:
      - Technologies Used: tech-used/tech_used.md
  - Initialize:
      - Set Up & Deployment: setup-and-deployment/setup_and_deployment.md
  - Snack:
      - Overview: developer-snack/developer_snack.md
      - Make Documentation: developer-snack/mkdoc/mkdoc.md
      - Developer Reminder: developer-snack/development_reminder.md
  - About:
      - About: about.md
      - License: LICENSE.md

# THEME
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: teal
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: indigo

# EXTRA
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/plexoio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plexoio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arellanofrank/

# EXTENSIONS
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # COPYRIGHT

copyright: |
  &copy; 2023 by <a href="https://github.com/plexoio"  target="_blank" rel="noopener">Frank Arellano</a> 
  with 
  <a href="https://www.mkdocs.org/"  target="_blank" rel="noopener">MkDocs</a>
